## Pandas Library in Python

In [1]:
#Data Science
#Artificial Intelligence
#Machine Learning
#Data Visualization

In [2]:
#Pandas is an open-source Python library designed for data manipulation and analysis with structured data fast, flexible and intuitive.

In [3]:
#csv files-comma separated files

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\kayrow\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kayrow\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kayrow\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kayrow\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kayrow\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kayrow\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
#The two core data structures in pandas

## Series -A 1D labeled array(like a column)
## DataFrame-A 2D labeled data structure(like a full spreadsheet or SQL table)

### What is a DataFrame?

In [6]:
#A DataFrame is a two-dimensional, tabular data structure with labeled rows and columns

# Key Features

In [7]:
#Labeled-based indexing
#Column-wise and row-wise operations
#Support for mixed data types
#Fast, vectorised operations (built on Numpy)

# Example DataFrame

In [9]:
import pandas as pd
df = pd.read_csv("C:\\Users\\kayrow\\Downloads\\studentscsv.csv")
print(df)

   ID   Name  Age            Course Grade
0   1   John   20              Math     A
1   2   Mary   22           Physics     B
2   3  Steve   21         Chemistry     A
3   4   Lucy   23           Biology     C
4   5   Mike   20  Computer Science     B

In [10]:
data = pd.read_csv("C:\\Users\\kayrow\\Downloads\\123.csv")
print(data)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price  OrderDate Shipped       Country
0   1200.0   6/1/2024     Yes           USA
1    150.0   6/3/2024      No        Canada
2    300.0   6/4/2024     Yes           UAE
3     45.0   6/5/2024     Yes     Singapore
4     80.0   6/6/2024      No        Mexico
5      5.0   6/7/2024     Yes           UAE
6    450.0   6/8/2024     Yes            UK
7    220.0   6/9/2024      No   South Korea
8      1.5  6/10/2024     Yes         Italy
9     35.0  6/11/2024     Yes         Japan
10    85.0  6/12/2024     Yes        France
11   180.0  6/13/2024      No         India
12    12.0  6/14/2024     Yes     Australia
13    25.0  6/15/2024     Yes         Spain
14   280.0  6/16/2024      No         China
15     8.0  6/17/2024     Yes         Egypt
16    45.0  6/18/2024     Yes        Poland
17    65.0  6/19/2024      No           USA
18    15.0  6/20/2024     Yes         Japan
19   120.0  6/21/2024     Yes  Saudi Arabia
20     3.5  6/22/2024      No        Canada
21    95.0  6/23/2024     Yes        Brazil
22    35.0  6/24/2024     Yes       Germany
23     4.0  6/25/2024      No      Pakistan
24    28.0  6/26/2024     Yes        Sweden
25    75.0  6/27/2024     Yes        France
26    22.0  6/28/2024      No     Argentina
27     2.5  6/29/2024     Yes        Russia
28   110.0  6/30/2024     Yes   South Korea
29    18.0   7/1/2024      No         Italy
30    32.0   7/2/2024     Yes       Morocco
31   140.0   7/3/2024     Yes       Germany
32    42.0   7/4/2024      No      Colombia
33     0.8   7/5/2024     Yes           USA
34    55.0   7/6/2024     Yes         Japan
35    68.0   7/7/2024      No            UK
36   125.0   7/8/2024     Yes      Portugal
37    28.0   7/9/2024     Yes          Iran
38    18.0  7/10/2024      No   South Korea
39    35.0  7/11/2024     Yes       Ukraine

# Exploring A DataFrame

In [11]:
data.head()   #First 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,6/1/2024,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,6/3/2024,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,6/4/2024,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,6/5/2024,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,6/6/2024,No,Mexico

In [12]:
data.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,7/7/2024,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,7/8/2024,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,7/9/2024,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,7/10/2024,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,7/11/2024,Yes,Ukraine

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

In [17]:
data.describe()  #Summary stats

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [18]:
data.columns #Column names

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [19]:
data.index  #Row index

RangeIndex(start=0, stop=40, step=1)

# Accessing And Filtering Data

In [21]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\kayrow\\Downloads\\studentscsv.csv")
print(df)

   ID   Name  Age            Course Grade
0   1   John   20              Math     A
1   2   Mary   22           Physics     B
2   3  Steve   21         Chemistry     A
3   4   Lucy   23           Biology     C
4   5   Mike   20  Computer Science     B

## Basic Access

In [22]:
df['Age']

0    20
1    22
2    21
3    23
4    20
Name: Age, dtype: int64

In [23]:
df[['Name','Age']]

    Name  Age
0   John   20
1   Mary   22
2  Steve   21
3   Lucy   23
4   Mike   20

In [24]:
df.iloc[0]

ID           1
Name      John
Age         20
Course    Math
Grade        A
Name: 0, dtype: object

In [25]:
df.loc[0]

ID           1
Name      John
Age         20
Course    Math
Grade        A
Name: 0, dtype: object

## Filtering

In [26]:
df[df['Age']< 23]

   ID   Name  Age            Course Grade
0   1   John   20              Math     A
1   2   Mary   22           Physics     B
2   3  Steve   21         Chemistry     A
4   5   Mike   20  Computer Science     B

In [29]:
df[df['Grade'] == 'A']

   ID   Name  Age     Course Grade
0   1   John   20       Math     A
2   3  Steve   21  Chemistry     A

In [32]:
df[(df['Age'] < 21) & (df['Grade'] =='A')]

   ID  Name  Age Course Grade
0   1  John   20   Math     A